VERSION: 24.2.0.0
PORT: 22501
# Normally this file will not be changed

component:
  # 各个组件配置信息,路径均为相对路径
  # head:  <组件名称>
  #   script_path: <启动脚本路径>  启动脚本路径,相对于安装目录路径
  #   directory_name: <目录名称>  显示脚本路径，找到启动脚本
  #   port: <端口号>  端口号
  # 启动顺序:  如果填写startup_sequence字段，按填写顺序启动，从1开始
  # 启动顺序： 不填写这个字段，值默认为-1，程序随机启动，无顺序
  # 启动顺序:  按顺序启动中间有失败，后续程序不再启动，无序启动，失败程序不影响后续程序启动

  apache-zookeeper:
    directory_name: "apache-zookeeper-3.8.0-bin"
    script_path: "bin/zkServer.sh"
    port: 2181
    keep-alive: False
    startup_sequence: 1

  grafana:
    directory_name: "grafana-7.4.3"
    script_path: "bin/run.sh"
    port: 9527

  emss-metric-exporters:
    directory_name: "emss-metric-exporters"
    script_path: "run.sh"
    port: 8081

  logstash:
    directory_name: "logstash-8.7.0"
    script_path: "bin/run.sh"

  flink:
    directory_name: "flink-1.17.1"
    script_path: "bin/run.sh"
    port: 8881

  emss-server:
    directory_name: "application"
    script_path: "start-emss.sh"
    port:
      - 8080
    startup_sequence: 3

  org.h2.tools.Server:
    directory_name: "application"
    script_path: "start-emss.sh  h2"
    port: 8085

  kafkaServer:
    directory_name: "kafka_2.12-2.6.0"
    script_path: "bin/run.sh"
    port: 9092
    startup_sequence: 2

  nginx:
    directory_name: "emss-web/nginx"
    script_path: "sbin/run.sh"
    port: 3500

  prometheus:
    directory_name: "monitor/prometheus"
    script_path: "run.sh"
    port: 9090

  alertmanager:
    directory_name: "monitor/alertmanager"
    script_path: "run.sh"
    port: 9093

  pushgateway:
    directory_name: "monitor/pushgateway"
    script_path: "run.sh"
    port: 9091

  elasticsearch:
    directory_name: "elasticsearch-7.6.2/bin"
    script_path: "run.sh"
    port: 9200

  postgres_exporter:
    directory_name: "monitor/export/postgres_exporter"
    script_path: "run.sh"
    port: 9187
